# Define the stages of your pipeline
stages:
  - build_image
  - deploy

# Define a cache for node_modules to speed up builds
cache:
  paths:
    - node_modules/

# Job to build and push the Docker image
build_and_push_docker_image:
  stage: build_image
  image: docker:latest
  services:
    - docker:dind

  script:
    - echo "Logging into GitLab Container Registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    - echo "Building Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .

    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

  rules:
    - if: $CI_COMMIT_BRANCH

# Placeholder for a deployment job
deploy_app:
  stage: deploy
  image: alpine/git
  script:
    - echo "Deployment job started. This is a placeholder."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual